site_name: Embedded Programs
site_url: https://beta.embeddedprograms.com
site_description: Embedded Programs
site_author: Sunil Kumar

theme:
  #  name: mkdocs
  name: material
  favicon: media/favicon.ico
  logo: media/favicon.ico
  palette:
    primary: 'teal'
    accent: 'yellow'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.tabs
#    - navigation.sections

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sunilk8
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2020 - 2022  Sunil Kumar  –
  <a href="#__consent">Change cookie settings</a>
  generator: false
