site_name: Embedded Programs
site_url: https://www.embeddedprograms.com
site_description: Embedded Programs
site_author: Sunil Kumar

theme:
  name: material
  favicon: resources/media/favicon.ico
  logo: resources/media/favicon.ico
  palette:
    primary: 'teal'
    accent: 'yellow'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.tabs
    #- navigation.sections
    #- navigation.top
    #- navigation.expand
    #- navigation.indexes
    #- toc.integrate 
    #- navigation.tracking
  #hide:
    #- toc
    #- navigation

extra_css:
  - resources/stylesheets/extra.css

extra_javascript:
  - resources/stylesheets/ga.js

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sunilk8
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: UA-49547207-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

# Page tree
#nav:
#  - Home: index.md
#  - About Me:
#    - profile/profile.md

copyright: >
  Copyright &copy; 2020 - 2023  Sunil Kumar  –
  <a href="#__consent">Change cookie settings</a>
  generator: false
